// @generated by `cargo run --locked -p lumin-xtask -- path-codec --write`.
// Source: specs/repo-path-semantics.v1.json
// Do not edit this file by hand.

pub const PATH_CODEC_ARTIFACT_SHA256: &str =
    "ee686f81164ff40b281483afaae591793964cc576afaca0ce7b5b51a6798b4a6";
pub const PATH_CODEC_TABLE_SHA256: &str =
    "325a6cfec9d3fe422ffe606d71c3f068d2205a175ea28921e96749febcc9c115";

pub const REPO_PATH_MAGIC: &[u8; 8] = b"LUMRPATH";
pub const REPO_PATH_VERSION: u16 = 1;
pub const PORTABLE_UTF8_TAG: u8 = 1;
pub const UNIX_BYTES_TAG: u8 = 2;
pub const WINDOWS_WTF16_TAG: u8 = 3;

pub const REPOSITORY_ROOT_MAGIC: &[u8; 8] = b"LUMRROOT";
pub const REPOSITORY_ROOT_VERSION: u16 = 1;
pub const UNIX_PLATFORM_TAG: u8 = 1;
pub const WINDOWS_PLATFORM_TAG: u8 = 2;
pub const UNIX_ABSOLUTE_TAG: u8 = 1;
pub const WINDOWS_DRIVE_TAG: u8 = 2;
pub const WINDOWS_UNC_TAG: u8 = 3;
pub const WINDOWS_VOLUME_GUID_TAG: u8 = 4;
pub const UNIX_PHYSICAL_IDENTITY_TAG: u8 = 1;
pub const WINDOWS_PHYSICAL_IDENTITY_TAG: u8 = 2;
