// @generated by `cargo run --locked -p lumin-xtask -- generated-tables --write`.
// Source: specs/inventory-config-semantics.v1.json
// Do not edit this file by hand.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FieldClassification {
    SupportedAndModeled,
    UnsupportedInventoryAffecting,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FieldPolicy {
    pub path: &'static str,
    pub shape: &'static str,
    pub classification: FieldClassification,
    pub reason: Option<&'static str>,
    pub limitation: Option<&'static str>,
    pub rule: Option<&'static str>,
    pub shape_mismatch_limitation: Option<&'static str>,
    pub applies_when: Option<&'static str>,
}

pub const INVENTORY_CONFIG_ARTIFACT_SHA256: &str =
    "ebca37c3b33f8e4d92ea29e0bcdc51b7cd5ea04a453c4c469a89072f3d2fac02";
pub const INVENTORY_CONFIG_TABLE_SHA256: &str =
    "c2bd7f00c8decf086d378b0723887f674a07387da77a6831936503722108b99c";

pub static INVENTORY_PACKAGE_JSON_FIELDS: &[FieldPolicy] = &[
    FieldPolicy {
        path: "dependencies",
        shape: "object<string,string>",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("dependency-ownership"),
        shape_mismatch_limitation: Some("DependencyOwnerAmbiguous"),
        applies_when: None,
    },
    FieldPolicy {
        path: "devDependencies",
        shape: "object<string,string>",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("dependency-ownership"),
        shape_mismatch_limitation: Some("DependencyOwnerAmbiguous"),
        applies_when: None,
    },
    FieldPolicy {
        path: "name",
        shape: "package-name.v1",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("package-identity-v1"),
        shape_mismatch_limitation: Some("PackageIdentityUnsupported"),
        applies_when: None,
    },
    FieldPolicy {
        path: "optionalDependencies",
        shape: "object<string,string>",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("dependency-ownership"),
        shape_mismatch_limitation: Some("DependencyOwnerAmbiguous"),
        applies_when: None,
    },
    FieldPolicy {
        path: "peerDependencies",
        shape: "object<string,string>",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("dependency-ownership"),
        shape_mismatch_limitation: Some("DependencyOwnerAmbiguous"),
        applies_when: None,
    },
    FieldPolicy {
        path: "private",
        shape: "boolean",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("private-package"),
        shape_mismatch_limitation: Some("PackagePrivacyUnsupported"),
        applies_when: None,
    },
    FieldPolicy {
        path: "workspaces",
        shape: "array<string>|object{packages:array<string>}",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("package-workspace-membership-v1"),
        shape_mismatch_limitation: Some("WorkspaceOwnershipUnsupported"),
        applies_when: None,
    },
];

pub static INVENTORY_PNPM_WORKSPACE_FIELDS: &[FieldPolicy] = &[
    FieldPolicy {
        path: "packages",
        shape: "array<string>",
        classification: FieldClassification::SupportedAndModeled,
        reason: None,
        limitation: None,
        rule: Some("pnpm-workspace-membership-v1"),
        shape_mismatch_limitation: Some("WorkspaceOwnershipUnsupported"),
        applies_when: None,
    },
    FieldPolicy {
        path: "catalog",
        shape: "object",
        classification: FieldClassification::UnsupportedInventoryAffecting,
        reason: None,
        limitation: Some("PnpmDependencySemanticsUnsupported"),
        rule: None,
        shape_mismatch_limitation: None,
        applies_when: None,
    },
    FieldPolicy {
        path: "catalogs",
        shape: "object",
        classification: FieldClassification::UnsupportedInventoryAffecting,
        reason: None,
        limitation: Some("PnpmDependencySemanticsUnsupported"),
        rule: None,
        shape_mismatch_limitation: None,
        applies_when: None,
    },
    FieldPolicy {
        path: "packageConfigs",
        shape: "any-pnpm-value",
        classification: FieldClassification::UnsupportedInventoryAffecting,
        reason: None,
        limitation: Some("PnpmDependencySemanticsUnsupported"),
        rule: None,
        shape_mismatch_limitation: None,
        applies_when: None,
    },
];

pub static INVENTORY_RESOLVER_OWNED_FIELDS: &[&str] = &[
    "browser",
    "exports",
    "imports",
    "main",
    "module",
    "react-native",
    "sideEffects",
    "tsconfig",
    "type",
    "types",
    "typesVersions",
    "typings",
];

pub(crate) fn package_json_field_for_rule(rule: &str) -> Option<&'static FieldPolicy> {
    INVENTORY_PACKAGE_JSON_FIELDS
        .iter()
        .find(|policy| policy.rule == Some(rule))
}

pub(crate) fn pnpm_workspace_field(path: &str) -> Option<&'static FieldPolicy> {
    INVENTORY_PNPM_WORKSPACE_FIELDS
        .iter()
        .find(|policy| policy.path == path)
}
